# Generated by Django 6.0.2 on 2026-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='static_image',
            field=models.CharField(blank=True, help_text='Example: tomato_soup.jpg (stored in static/recipes/images/)', max_length=200),
        ),
    ]
